name: ci

on:
  push:
    branches: [develop]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci
      # Set the DB connection string
      - name: Set DB connection string
        run: |
          echo "TEST_DB=${{ secrets.TEST_DB }}" >> $GITHUB_ENV
          echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" >> $GITHUB_ENV
          echo "BACKEND_LIVE_URL=${{ secrets.BACKEND_LIVE_URL }}" >> $GITHUB_ENV
          echo "CLIENT_URL=${{ secrets.CLIENT_URL }}" >> $GITHUB_ENV
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> $GITHUB_ENV
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> $GITHUB_ENV
          echo "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_CALLBACK=${{ secrets.GOOGLE_CLIENT_CALLBACK }}" >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> $GITHUB_ENV
          echo "CLIENT_LOCALHOST_URL=${{ secrets.CLIENT_LOCALHOST_URL }}" >> $GITHUB_ENV
          echo "CLIENT_LOCALHOST_URL=${{ secrets.CLIENT_LOCALHOST_URL }}" >> $GITHUB_ENV
          echo "GMAIL_USER=${{ secrets.GMAIL_USER }}" >> $GITHUB_ENV
          echo "GMAIL_APP_PASSWORD=${{ secrets.GMAIL_APP_PASSWORD }}" >> $GITHUB_ENV
          echo "PAYPACK_APP_ID=${{ secrets.PAYPACK_APP_ID }}" >> $GITHUB_ENV
          echo "PAYPACK_APP_SECRET=${{ secrets.PAYPACK_APP_SECRET }}" >> $GITHUB_ENV
          echo "FLW_SECRET_KEY=${{ secrets.FLW_SECRET_KEY }}" >> $GITHUB_ENV
          echo "FLW_PUBLIC_KEY=${{ secrets.FLW_PUBLIC_KEY }}" >> $GITHUB_ENV
          echo "FLW_ECRYPTION_KEY=${{ secrets.FLW_ECRYPTION_KEY }}" >> $GITHUB_ENV
      - run: npm test
